apiVersion: apps/v1
kind: Deployment
metadata:
  name: kareldb
  labels:
    app: kareldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kareldb
  template:
    metadata:
      labels:
        app: kareldb
    spec:
      containers:
      - name: kareldb
        image: ohkinozomu/kareldb:1.0.3-0.1.0
        command: ["bin/kareldb-start", "config/kareldb.properties"]
        ports:
        - containerPort: 8765
        volumeMounts:
          - name: kareldb
            mountPath: /usr/local/src/config/kareldb.properties
            subPath: kareldb.properties
            readOnly: true
      volumes:
      - name: kareldb
        configMap:
          name: kareldb
          items:
          - key: kareldb.properties
            path: kareldb.properties
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kareldb
data:
  kareldb.properties: |
    listeners=http://0.0.0.0:8765
    cluster.group.id=kareldb
    kafkacache.bootstrap.servers=your-kafka-cluster-bootstrap:9092
    kafkacache.group.id=kareldb-1
    kafkacache.backing.cache=rocksdb
    kafkacache.data.dir=/tmp
    debug=false